// Sample data — Collaburo admin workflow steps + fields.
// Field types align with what the user selected:
// text, textarea, number, select, multiselect, date, daterange, file, price, toggle, room, addons

const SAMPLE_STEPS = [
  {
    id: "s1",
    name: "Personal Details",
    description: "Who is booking the event? We use this to follow up and put a name on the calendar.",
    icon: "Users",
    fields: [
      { id: "f1", label: "Client First Name", type: "text", required: true, adminRequired: false,
        placeholder: "Enter first name", helpText: "", visibleToClient: true,
        internalNote: "", linkedToPricing: false, category: "Contact" },
      { id: "f2", label: "Last Name", type: "text", required: true, adminRequired: false,
        placeholder: "Enter last name", visibleToClient: true, category: "Contact" },
      { id: "f3", label: "Organization", type: "text", required: false, adminRequired: false,
        placeholder: "Enter organization or charity name if any",
        helpText: "If booking on behalf of a business, non-profit, or organization.",
        visibleToClient: true, category: "Contact" },
      { id: "f4", label: "Email", type: "text", required: true, adminRequired: false,
        placeholder: "Enter email address", visibleToClient: true, category: "Contact" },
      { id: "f5", label: "Phone Number", type: "number", required: true, adminRequired: false,
        placeholder: "Enter valid phone number: (123) 123-1234", visibleToClient: true, category: "Contact" },
      { id: "f6", label: "Not for profit",
        type: "toggle", required: false, adminRequired: false,
        fieldDescription: "(only check this if you are a registered charity or a not for profit organization)",
        visibleToClient: true, linkedToPricing: true, category: "Discount" },
      { id: "f7", label: "Student Body",
        type: "toggle", required: false, adminRequired: true,
        fieldDescription: "(only check this if event is fully related to a school or university/college)",
        visibleToClient: true, linkedToPricing: true, category: "Discount",
        visibility: { field: "Organization", op: "has_value" } },
    ],
  },
  {
    id: "s2",
    name: "Event Details",
    description: "Tell us about your event so we can match it to the right space and services.",
    icon: "Cal",
    fields: [
      { id: "f10", label: "Event Privacy", type: "radio", required: true, visibleToClient: true,
        options: [
          "Public|Events that are advertised publicly, tickets sold/given in advance or at the door.",
          "Semi-private|A mostly private event but some guests may be from the general public.",
          "Private|A private event for family, friends, coworkers, or invited guests only."
        ],
        category: "Event" },
      { id: "f11", label: "Event Type", type: "select", hasOptions: true, displayAs: "select", groupOptions: true, required: true, visibleToClient: true,
        placeholder: "Select one event type",
        options: [
          { type: "group", label: "Business", options: [
            { label: "Business / Board Meeting" },
            { label: "Conference" },
            { label: "Workshop / Training" },
            { label: "Other - Business" },
          ]},
          { type: "group", label: "Social", options: [
            { label: "Lecture / Theater / Movie" },
            { label: "Social Event with dancing / Party" },
            { label: "Social Event without dancing / Banquet" },
            { label: "Reception / Cocktail Party" },
            { label: "Wedding & Reception" },
            { label: "Ceremony / Graduation" },
            { label: "Memorial / End of Life Celebration" },
            { label: "Festival / Market / Show" },
            { label: "Other - Social" },
          ]},
        ],
        category: "Event" },
      { id: "f12", label: "Brief Description of Event", type: "text", required: true,
        placeholder: 'What type of event is this? (ex. "1st Bday", "Family Gathering")',
        visibleToClient: true, category: "Event" },
      { id: "f13", label: "Alcohol on Site", type: "radio", required: true, visibleToClient: true,
        options: [
          "Yes|There will be alcohol/liquor/wine served at the event.",
          "No|There will not be any alcohol served at the event."
        ],
        category: "Event" },
      { id: "f14", label: "Expected Number of Attendees", type: "number", required: true,
        placeholder: "30", visibleToClient: true, category: "Event", min: 10, max: 500 },
    ],
  },
  {
    id: "s3",
    name: "Venue Space",
    description: "Select the space that best fits your event.",
    icon: "Building",
    stepType: "venue",
    fields: [],
    venues: [
      {
        id: "v1", name: "Main Hall", active: true, visibility: "admin_and_user",
        thumbnail: null,
        gallery: [],
        venueCapacity: 120,
        suitableEventTypes: ["Conference", "Workshop / Training", "Social Event with dancing / Party", "Social Event without dancing / Banquet", "Reception / Cocktail Party", "Wedding & Reception", "Ceremony / Graduation", "Festival / Market / Show"],
        description: "All you need to host your corporate meetings, conferences, dinners, special events, wedding, etc. The Main Hall is about 1500 sqft (with a possibility to extend up to 1900 sqft with the Elevated Area) features a stage with a beautiful tree mural, 90 fabric chairs, a sound system, projector, and a kitchenette. It also has natural light and high cathedral ceilings, perfect for large events.",
        equippedWith: "Beautiful High Cathedral Ceiling\n90 Fabric Chairs\nStage with a Beautiful Mural on Stage Wall\nSpeakers and wired Microphone (with stand)\nWi-Fi Internet (high speed)\nAssisted Elevator Access (to stage and part of hall)\nNatural Light, Dimmable Lights and Disco Lights\nA/C, Heating and 2 adjustable ceiling fans",
        byRequest: "Buffet tables with wipeable tablecloths\nBackdrop + Panel Covers\nWindows Covers\nTables + Linens\nOther type of chairs\nDinnerware + Utensils\nMC Podium\nProjector + 150\" projector screen\nSmart TV\nWhiteboard\nVideo/Audio Conference for video calls",
        maxCapacity: "Rectangular Tables - 76 people\nCircular Tables - 70 people\nTheater Style - 110 people\nCocktail / Reception - 120 people\nConference Room - 36 people (or 60 people with double rows)\nClassroom Style - 50 people",
        pricing: [
          { id: "pp1", rateType: "per_hour", basePrice: 1555, includedHours: 4, extraHourRate: 745 },
          { id: "pp2", rateType: "per_day", basePrice: 3985, includedHours: 10, extraHourRate: 245 },
        ],
        advancedPricing: {
          setupFee: 99, cleanupFee: 99, securityDeposit: 100,
          bookingMinHours: 4, bookingMinUnit: "hours",
          discountEligible: true,
          bookingHours: { mon: "07:00-23:00", tue: "07:00-23:00", wed: "07:00-23:00", thu: "07:00-23:00", fri: "07:00-23:00", sat: "08:00-23:00", sun: "07:00-23:00" },
          holdAmount: 50, holdType: "percentage",
          finalAmount: 50, finalType: "percentage", finalDaysBefore: 7,
          cancellationPolicy: "Full refund will be given for cancellation requested up to 20 business days prior to the start date. The deposit is non-refundable if cancellation occurs less than 20 business days before the event. All fees are non-refundable if cancellation occurs 5 business days or less before the event.",
        },
        subSpace: {
          enabled: true,
          title: "Optional Extension (Elevated Area)",
          description: "This Elevated space is an extension of the Main Hall and has its own entrance. The attendees sitting in this space can see the Main Hall and stage. The space does not come with any content.",
          options: [
            { id: "ss1", name: "Full Area", price: 800, description: "The Full Elevated Area adds about 300 sqft to the Main Hall\n+ 30 seats for round tables", thumbnail: null, gallery: [] },
            { id: "ss2", name: "Half Area", price: 600, description: "Half of the Elevated Area\n+ 16 seats for round tables", thumbnail: null, gallery: [] },
            { id: "ss3", name: "Deep Half Area", price: 400, description: "The deep section of the Elevated Area\n+ 10 seats", thumbnail: null, gallery: [] },
          ],
        },
      },
      {
        id: "v2", name: "Large Room", active: true, visibility: "admin_and_user",
        thumbnail: null, gallery: [],
        venueCapacity: 60,
        suitableEventTypes: ["Conference", "Workshop / Training", "Business / Board Meeting", "Lecture / Theater / Movie", "Social Event without dancing / Banquet"],
        description: "A spacious room ideal for medium-sized events, training sessions, and corporate meetings. Features modern amenities and flexible layout options.",
        equippedWith: "Projector + Screen\nWhiteboard\nWi-Fi Internet\nA/C and Heating\n40 Cushion Chairs\nConference Phone",
        byRequest: "Catering setup\nAdditional tables\nVideo conferencing equipment",
        maxCapacity: "Rectangular Tables - 40 people\nTheater Style - 60 people\nConference Room - 24 people\nClassroom Style - 30 people",
        pricing: [
          { id: "pp3", rateType: "per_hour", basePrice: 1355, includedHours: 4, extraHourRate: 245 },
          { id: "pp4", rateType: "per_day", basePrice: 3565, includedHours: 10, extraHourRate: 245 },
        ],
        advancedPricing: {
          setupFee: 50, cleanupFee: 50, securityDeposit: 100,
          bookingMinHours: 4, bookingMinUnit: "hours", discountEligible: true,
          bookingHours: { mon: "07:00-23:00", tue: "07:00-23:00", wed: "07:00-23:00", thu: "07:00-23:00", fri: "07:00-23:00", sat: "08:00-23:00", sun: "07:00-23:00" },
          holdAmount: 50, holdType: "percentage",
          finalAmount: 50, finalType: "percentage", finalDaysBefore: 7,
          cancellationPolicy: "Full refund will be given for cancellation requested up to 20 business days prior to the start date.",
        },
        subSpace: { enabled: false, title: "", description: "", options: [] },
      },
      {
        id: "v3", name: "Small Room", active: true, visibility: "admin_and_user",
        thumbnail: null, gallery: [],
        venueCapacity: 6,
        suitableEventTypes: ["Business / Board Meeting"],
        description: "A cozy room perfect for intimate meetings, interviews, and small gatherings.",
        equippedWith: "Whiteboard\nWi-Fi Internet\nA/C\n6 Chairs\nTable",
        byRequest: "Projector\nConference phone",
        maxCapacity: "Conference - 6 people\nMeeting - 4 people",
        pricing: [
          { id: "pp5", rateType: "per_hour", basePrice: 60, includedHours: 2, extraHourRate: 30 },
        ],
        advancedPricing: {
          setupFee: 0, cleanupFee: 0, securityDeposit: 50,
          bookingMinHours: 2, bookingMinUnit: "hours", discountEligible: false,
          bookingHours: { mon: "07:00-23:00", tue: "07:00-23:00", wed: "07:00-23:00", thu: "07:00-23:00", fri: "07:00-23:00", sat: "08:00-23:00", sun: "07:00-23:00" },
          holdAmount: 100, holdType: "percentage",
          finalAmount: 0, finalType: "percentage", finalDaysBefore: 0,
          cancellationPolicy: "Full refund if cancelled 5 business days prior.",
        },
        subSpace: { enabled: false, title: "", description: "", options: [] },
      },
      {
        id: "v4", name: "Lounge Area", active: true, visibility: "admin_and_user",
        thumbnail: null, gallery: [],
        venueCapacity: 30,
        suitableEventTypes: ["Reception / Cocktail Party", "Social Event without dancing / Banquet"],
        description: "A comfortable lounge space with soft seating, ideal for receptions, cocktail hours, and casual networking events.",
        equippedWith: "Soft seating for 20\nCoffee tables\nAmbient lighting\nWi-Fi Internet\nBluetooth speakers",
        byRequest: "Bar setup\nCocktail tables",
        maxCapacity: "Cocktail / Standing - 30 people\nSeated - 20 people",
        pricing: [
          { id: "pp6", rateType: "per_hour", basePrice: 100, includedHours: 2, extraHourRate: 50 },
        ],
        advancedPricing: {
          setupFee: 0, cleanupFee: 0, securityDeposit: 50,
          bookingMinHours: 2, bookingMinUnit: "hours", discountEligible: false,
          bookingHours: { mon: "07:00-23:00", tue: "07:00-23:00", wed: "07:00-23:00", thu: "07:00-23:00", fri: "07:00-23:00", sat: "08:00-23:00", sun: "07:00-23:00" },
          holdAmount: 100, holdType: "percentage",
          finalAmount: 0, finalType: "percentage", finalDaysBefore: 0,
          cancellationPolicy: "Full refund if cancelled 5 business days prior.",
        },
        subSpace: { enabled: false, title: "", description: "", options: [] },
      },
      {
        id: "v5", name: "Back Patio", active: true, visibility: "admin_and_user",
        thumbnail: null, gallery: [],
        venueCapacity: 50,
        suitableEventTypes: ["Reception / Cocktail Party", "Social Event with dancing / Party", "Festival / Market / Show"],
        description: "An outdoor patio space perfect for BBQs, garden parties, and open-air events. Available as a standalone rental or add-on to Main Hall bookings.",
        equippedWith: "Outdoor lighting\nGarden area\nBBQ station access\nPicnic tables",
        byRequest: "Tent / canopy\nOutdoor heaters\nString lights",
        maxCapacity: "Standing - 50 people\nSeated - 30 people",
        pricing: [
          { id: "pp7", rateType: "per_hour", basePrice: 140, includedHours: 2, extraHourRate: 70 },
        ],
        advancedPricing: {
          setupFee: 0, cleanupFee: 0, securityDeposit: 50,
          bookingMinHours: 2, bookingMinUnit: "hours", discountEligible: false,
          bookingHours: { mon: "07:00-21:00", tue: "07:00-21:00", wed: "07:00-21:00", thu: "07:00-21:00", fri: "07:00-22:00", sat: "08:00-22:00", sun: "07:00-21:00" },
          holdAmount: 100, holdType: "percentage",
          finalAmount: 0, finalType: "percentage", finalDaysBefore: 0,
          cancellationPolicy: "Full refund if cancelled 3 business days prior.",
        },
        subSpace: { enabled: false, title: "", description: "", options: [] },
      },
    ],
  },
  {
    id: "s4",
    name: "Layout",
    description: "Choose how the room will be arranged — floor plan, seating, and stage layout.",
    icon: "Layers",
    stepType: "layout",
    fields: [
      { id: "f_layout_tables", label: "Tables", type: "rental_group", rentalGroup: "Tables", rentalDisplayMode: "separate_items", rentalPreviewHeading: "Space Contents", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals", fieldDescription: "Tables connected to the selected layout and any extras the client may need." },
      { id: "f_layout_chairs", label: "Chairs", type: "rental_group", rentalGroup: "Chairs", rentalDisplayMode: "grouped", rentalPreviewHeading: "Space Contents", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals", fieldDescription: "Chairs connected to the selected layout and any extras the client may need." },
    ],
    spaceRequirements: [
      { id: "sr1", name: "Buffet/Food Table", icon: "🍽️", active: true },
      { id: "sr2", name: "Bar Table", icon: "🍸", active: true },
      { id: "sr3", name: "Dance Area", icon: "💃", active: true },
      { id: "sr4", name: "Photo Booth Area (photo booth not included)", icon: "📷", active: true },
      { id: "sr5", name: "DJ Table / Area", icon: "🎧", active: true },
      { id: "sr6", name: "Cake Table", icon: "🎂", active: true },
      { id: "sr7", name: "Welcome / Registration Table", icon: "📋", active: true },
      { id: "sr8", name: "Favours / Guestbook Table", icon: "📖", active: true },
      { id: "sr9", name: "Clean-up Area (used by servers)", icon: "🧹", active: true },
    ],
    floorLayouts: {
      v1: {
        layouts: [
          {
            id: "fl1", name: "Rectangular tables with buffet area on raised area (max 70 people)",
            image: "", capacityMin: 50, capacityMax: 70,
            applicableEventTypes: ["Social Event with dancing / Party", "Social Event without dancing / Banquet", "Wedding & Reception"],
            applicableSpaceReqs: ["sr1", "sr3", "sr7", "sr8", "sr9"],
            recommendedFor: 70,
            recommendedDescription: "Above layout includes:\n- 3 Rectangular 6' Tables\n- 5 Rectangular 8' Tables\n- 70 Rust Chairs",
          },
          {
            id: "fl2", name: "Rectangular tables with dance floor on side (max 76 people)",
            image: "", capacityMin: 40, capacityMax: 76,
            applicableEventTypes: ["Social Event with dancing / Party", "Wedding & Reception", "Reception / Cocktail Party"],
            applicableSpaceReqs: ["sr1", "sr2", "sr3", "sr5", "sr9"],
            recommendedFor: 76,
            recommendedDescription: "Above layout includes:\n- 4 Rectangular 6' Tables\n- 5 Rectangular 8' Tables\n- 76 Rust Chairs",
          },
          {
            id: "fl3", name: "Rectangular tables with dance floor near stage (max # people)",
            image: "", capacityMin: 30, capacityMax: 60,
            applicableEventTypes: ["Social Event with dancing / Party", "Conference", "Ceremony / Graduation"],
            applicableSpaceReqs: ["sr1", "sr3", "sr5"],
            recommendedFor: 60,
            recommendedDescription: "Above layout includes:\n- 3 Rectangular 6' Tables\n- 4 Rectangular 8' Tables\n- 60 Rust Chairs",
          },
          {
            id: "fl4", name: "Circular tables with buffet on raised area (max # of people)",
            image: "", capacityMin: 40, capacityMax: 70,
            applicableEventTypes: ["Social Event without dancing / Banquet", "Wedding & Reception", "Ceremony / Graduation"],
            applicableSpaceReqs: ["sr1", "sr6", "sr7", "sr9"],
            recommendedFor: 70,
            recommendedDescription: "Above layout includes:\n- 8 Round Tables\n- 70 Rust Chairs",
          },
        ],
        blankFloorPlan: "",
      },
      v2: {
        layouts: [
          {
            id: "fl10", name: "Extra Seating Banquet V2",
            image: "", capacityMin: 10, capacityMax: 30,
            applicableEventTypes: ["Social Event without dancing / Banquet", "Wedding & Reception"],
            applicableSpaceReqs: [],
            recommendedFor: 30,
            recommendedDescription: "Additional capacity: +30 people\n# Rectangular 6' Tables\n# Rectangular 8' Tables\n# Rust Chairs",
          },
          {
            id: "fl11", name: "Extra Seating Banquet V3",
            image: "", capacityMin: 10, capacityMax: 30,
            applicableEventTypes: ["Social Event without dancing / Banquet", "Wedding & Reception"],
            applicableSpaceReqs: [],
            recommendedFor: 30,
            recommendedDescription: "Additional capacity: +30 people\n# Rectangular 6' Tables\n# Rectangular 8' Tables\n# Rust Chairs",
          },
          {
            id: "fl12", name: "Extra Round Banquet V1",
            image: "", capacityMin: 10, capacityMax: 24,
            applicableEventTypes: ["Social Event without dancing / Banquet", "Wedding & Reception"],
            applicableSpaceReqs: [],
            recommendedFor: 24,
            recommendedDescription: "Additional capacity: +24 people\n# Round Tables\n# Rust Chairs",
          },
        ],
        blankFloorPlan: "",
      },
      v4: {
        layouts: [
          {
            id: "fl20", name: "Lounge Style Seating",
            image: "", capacityMin: 10, capacityMax: 30,
            applicableEventTypes: ["Reception / Cocktail Party", "Business / Board Meeting"],
            applicableSpaceReqs: ["sr2"],
            recommendedFor: 30,
            recommendedDescription: "Lounge area with bar setup\n- 4 Cocktail Tables\n- Lounge seating",
          },
        ],
        blankFloorPlan: "",
      },
      v5: {
        layouts: [
          {
            id: "fl30", name: "Outdoor rectangular setup",
            image: "", capacityMin: 20, capacityMax: 50,
            applicableEventTypes: ["Social Event with dancing / Party", "Reception / Cocktail Party", "Festival / Market / Show"],
            applicableSpaceReqs: ["sr1", "sr2", "sr3"],
            recommendedFor: 50,
            recommendedDescription: "Patio setup includes:\n- 4 Rectangular 8' Tables\n- 50 Chairs",
          },
        ],
        blankFloorPlan: "",
      },
    },
    rentals: {},
  },
  {
    id: "s5",
    name: "Rentals",
    description: "Select additional rentals for your event — furniture, AV, and décor.",
    icon: "Tag",
    fields: [
      { id: "f_rent_centerpieces", label: "Centerpieces", type: "rental_group", rentalGroup: "Centerpieces", rentalDisplayMode: "grouped", rentalPreviewHeading: "Rental Groups", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals" },
      { id: "f_rent_dinnerware", label: "Dinnerware", type: "rental_group", rentalGroup: "Dinnerware", rentalDisplayMode: "grouped", rentalPreviewHeading: "Rental Groups", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals" },
      { id: "f_rent_tech", label: "Tech", type: "rental_group", rentalGroup: "AV / Tech", rentalDisplayMode: "grouped", rentalPreviewHeading: "Rental Groups", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals" },
      { id: "f_rent_others", label: "Others", type: "rental_group", rentalGroup: "Decor / Other", rentalDisplayMode: "grouped", rentalPreviewHeading: "Rental Groups", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals" },
      { id: "f_rent_extras", label: "Extras", type: "extras", required: false, visibleToClient: true, linkedToPricing: true, category: "Rentals",
        amountLabel: "Total Extra Amount", descriptionLabel: "Description",
        placeholder: "Enter any details here for any item you wish to have at your event that is not listed above.\nCollaburo will try to get you the items you are looking for but makes no promises." },
    ],
  },
  {
    id: "s6",
    name: "Catering",
    description: "Beverage packages, buffet options, and catering preferences.",
    icon: "Tag",
    fields: [
      { id: "f50", label: "Beverage Package", type: "radio", hasOptions: true, required: false, visibleToClient: true,
        helpText: "Select your preferred beverage service package",
        displayAs: "radio",
        subOptionDisplayAs: "radio",
        selectionDisplayAs: "checkbox",
        specificationDisplayAs: "checkbox",
        options: [
          { label: "Hot/Cold Beverages (Coffee, Tea, Soft Drinks)", enablePrice: false,
            infoText: "Includes service staff, dispensers, and a curated drink list for the duration of your event.",
            hasSubOptions: true, subOptions: [
              { label: "Up to 30 People", price: 10, enablePrice: true,
                infoText: "Best for intimate gatherings and small meetings.",
                hasSelections: true, selections: [
                  { label: "Coffee only", price: 10, enablePrice: true,
                    infoText: "Premium fair-trade beans, fresh-brewed throughout the event.",
                    hasSpecifications: true, specifications: [
                      { label: "Whole milk", price: 0 },
                      { label: "Oat milk", price: 2, enablePrice: true },
                      { label: "Sugar-free syrup", price: 1, enablePrice: true },
                    ]},
                  { label: "Coffee and Tea", price: 11, enablePrice: true,
                    hasSpecifications: true, specifications: [
                      { label: "Black tea" },
                      { label: "Green tea" },
                      { label: "Herbal tea", price: 1, enablePrice: true },
                    ]},
                ]},
              { label: "Up to 50 People", price: 18, enablePrice: true,
                hasSelections: true, selections: [
                  { label: "Coffee only" },
                  { label: "Coffee and Tea" },
                  { label: "Coffee, Tea, and Soft Drinks", price: 4, enablePrice: true },
                ]},
              { label: "Up to 100 People", price: 32, enablePrice: true },
            ]},
          { label: "No beverages required" }
        ],
        category: "Catering" },
      { id: "f51", label: "Buffet Table with Wipeable Covers", type: "checkbox", displayAs: "radio",
        required: false, visibleToClient: true,
        fieldDescription: "for Main Hall",
        options: [
          { label: "12'", price: 10, enablePrice: true },
          { label: "16'" },
          { label: "18'" },
          { label: "24'" }
        ],
        category: "Catering" },
      { id: "f52", label: "Buffet Tables Spandex Covers", type: "checkbox", displayAs: "select",
        required: false, visibleToClient: true,
        helpText: "Number of spandex covers needed",
        options: [
          { label: "1" }, { label: "2" }, { label: "3" }, { label: "4" }, { label: "5" }, { label: "6" }
        ],
        category: "Catering" },
      { id: "f53", label: "Do you require catering?", type: "radio", hasOptions: true,
        displayAs: "radio", subOptionDisplayAs: "checkbox",
        required: true, visibleToClient: true,
        options: [
          { label: "No, there will be no food at the event" },
          { label: "No, I will be bringing my own catered food and/or snacks." },
          { label: "Yes, please provide me catering options for",
            hasSubOptions: true, subOptions: [
              { label: "Breakfast" },
              { label: "Lunch" },
              { label: "Dinner" },
              { label: "Snack Food" }
            ]}
        ],
        category: "Catering" },
      { id: "f54", label: "Catering Specifics ( + for an additional cost )", type: "textarea",
        required: false, visibleToClient: true,
        placeholder: "Specify the catering you would like Collaburo to organize for you (ex. Continental Breakfast, Italian Dinner, etc) with the budget in mind. This will not be included in the quote and will be calculated separately.",
        visibility: { fieldId: "f53", op: "contains", value: "Yes" },
        category: "Catering" },
      { id: "f55", label: "Catering Delivery Time", type: "time", required: false, visibleToClient: true,
        placeholder: "02:00 PM",
        visibility: { fieldId: "f53", op: "contains", value: "Yes" },
        category: "Catering" },
      { id: "f56", label: "Dietary Restrictions", type: "multiselect", hasOptions: true, displayAs: "checkbox",
        required: false, adminRequired: true, visibleToClient: true,
        fieldDescription: "Check all dietary restrictions that apply.",
        options: [
          { label: "Halal" },
          { label: "Kosher" },
          { label: "Vegetarian" },
          { label: "Vegan" },
          { label: "Allergen Free" },
          { label: "Gluten-free" },
        ],
        category: "Catering" },
    ],
  },
  {
    id: "s7",
    name: "Additional Services",
    description: "Setup, event-day, cleanup services, and third-party vendors.",
    icon: "Cards",
    stepType: "services",
    fields: [
      // Set up Services — radio (one choice), each with description + optional price
      { id: "f60", label: "Set up Services", type: "radio", hasOptions: true, displayAs: "radio",
        required: false, visibleToClient: true, linkedToPricing: true,
        fieldDescription: "Collaburo has 3 types of set-up services to choose from",
        options: [
          { label: "Budget-friendly DIY Set-up Service", enablePrice: true, price: 0, pricingStructure: "included",
            infoText: "Full room layout with placement of furniture as per agreed plan including linens and chair covers (if rented through Collaburo)." },
          { label: "Concierge Set-up Service (Banquet)", enablePrice: true, price: 2.25, pricingStructure: "per_person",
            hasPeopleOption: true, peopleLinkedToGuests: true,
            infoText: "Same as the DIY Option, with full dinner service layout on tables (dishes, glasses, cutlery, napkins, centerpieces, chafing dishes, utensils) as well as buffet set up (adding hot water to chafing dishes and wrapping cutlery if needed). All items need to be provided by 7pm the evening before the event to a Collaburo staff (unless rented through Collaburo)." },
          { label: "Concierge Set-up Service (Reception/Cocktail Buffet)", enablePrice: true, price: 50, pricingStructure: "flat",
            infoText: "$50 flat fee for up to 1 hour, $25 per additional hour. Same as the DIY Option, with the set up of the buffet table. All items need to be provided by 7pm the evening before the event to a Collaburo staff (unless rented through Collaburo)." },
        ],
        category: "Services" },

      // Event Services — multiselect (multiple checkboxes), each priced per hour
      { id: "f61", label: "Event Services", type: "multiselect", hasOptions: true, displayAs: "checkbox",
        required: false, visibleToClient: true, linkedToPricing: true,
        options: [
          { label: "Server", enablePrice: true, price: 30, pricingStructure: "per_person_hour",
            hasSexOption: true, sexOptions: ["No Preference", "Male Only", "Female Only"],
            hasPeopleOption: true, peopleRange: { min: 1, max: 20 },
            hasHoursOption: true, hoursRange: { min: 1, max: 12 },
            infoText: "Designated Collaburo staff (with black pants/shirt and Collaburo apron) will be the server for your event. These staff will help in all aspects of the event: Serve food at a buffet; Plate food with table service; Clear plates between courses; Cut cake, plate and serve; set-up and clear-up chafing dishes and buffet; Clear up small messes/spills during event; clear tables, buffet and handle recycling as per our Walk away service. Generally 1 waiter is required for every 25 attendees. EXCEPTIONS: No alcohol related tasks. No selling services either." },
          { label: "Security Services", enablePrice: true, price: 33, pricingStructure: "per_person_hour",
            hasPeopleOption: true, peopleRange: { min: 1, max: 10 },
            hasHoursOption: true, hoursRange: { min: 1, max: 12 },
            infoText: "Security Guards experienced in events are required for Public events (where guests are unknown to the client or the event is advertised on social media) but optional for private events. Guards will be on site for the period between guests arrival and departure unless requested to be on site at the beginning of the booking period." },
          { label: "Event Planner", enablePrice: true, price: 30, pricingStructure: "per_hour",
            hasHoursOption: true, hoursRange: { min: 1, max: 40 },
            infoText: "Time spent helping the organizer plan last-minute details in the weeks leading up to the big event. Creating a timeline for the day, coordinating with 3rd party vendors for delivery, set-up and pick-up." },
          { label: "Coordinator Services during event", enablePrice: true, price: 30, pricingStructure: "per_hour",
            hasHoursOption: true, hoursRange: { min: 1, max: 12 },
            infoText: "Client can request for one of our experienced Event Managers to be on site for a period or entire time of their event. They will ensure the smooth running of the event on the day itself; essentially, they take charge of every detail to make the event successful." },
          { label: "IT Services", enablePrice: true, price: 60, pricingStructure: "per_hour",
            hasHoursOption: true, hoursRange: { min: 1, max: 12 },
            infoText: "Basic IT services such as connecting to the Wi-Fi, projector, and sound system are included in your rental and can be handled at the start of the event. For additional IT services such as manning the PTZ camera or controlling microphones, additional fees apply." },
        ],
        category: "Services" },

      // Notes textarea for event services
      { id: "f64", label: "Notes", type: "textarea", required: false, visibleToClient: true,
        placeholder: "Please fill in any details about the required work.",
        category: "Services" },

      // Clean-up Services — radio (one choice)
      { id: "f62", label: "Clean-up Services", type: "radio", hasOptions: true, displayAs: "radio",
        required: false, visibleToClient: true, linkedToPricing: true,
        fieldDescription: "Once an event is done, Collaburo has 3 types of clean-up services to choose from",
        options: [
          { label: "Budget-friendly DIY Clean-up Service", enablePrice: true, price: 0, pricingStructure: "included",
            infoText: "Client is expected to take home all their belongings (including any 3rd party items that the client rented without Collaburo's help, or have 3rd party items picked up at end of event), and recycle into the appropriate garbage/recycle/compost bins. If 3rd party rentals require pickup, the client is responsible for coordinating with the 3rd party." },
          { label: "Walk-Away Service (Banquet)", enablePrice: true, price: 2.75, pricingStructure: "per_person",
            hasPeopleOption: true, peopleLinkedToGuests: true,
            infoText: "Leave the space as if leaving a restaurant. Client is still expected to take home all their belongings (including any 3rd party items not rented through Collaburo). 1 hour of this service is included in the booking period." },
          { label: "Walk-Away Service (Reception/Cocktail Buffet)", enablePrice: true, price: 60, pricingStructure: "flat",
            infoText: "$60 flat fee for up to 2 hours, $25 per additional hour. Walk-Away Service from a reception/cocktail space without doing any cleaning. Client is still expected to take home all their belongings (including any 3rd party items not rented through Collaburo)." },
        ],
        category: "Services" },

      // 3rd Party Services — multiselect (vendor partner requests, no per-item pricing)
      { id: "f63", label: "3rd Party Services", type: "multiselect", hasOptions: true, displayAs: "checkbox",
        required: false, visibleToClient: true,
        fieldDescription: "Please check possible services you may require, and we will send your contact information and request to a few of our partners to connect with you and get you a quote.",
        options: [
          { label: "Bridal Package" },
          { label: "Child Minding" },
          { label: "Decorators" },
          { label: "Disc Jockey (DJ)" },
          { label: "Entertainers / Clowns" },
          { label: "Event Planners" },
          { label: "Floral Wall / Balloon Stylist" },
          { label: "Florist" },
          { label: "Helper" },
          { label: "Hotels" },
          { label: "Master of Ceremony (MC)" },
          { label: "Officiant" },
          { label: "Photobooth" },
          { label: "Photographers" },
          { label: "Transportation Services (car, van, bus, limo, etc.)" },
          { label: "Videographers" },
          { label: "Waiter / Server (Smart Serve)" },
        ],
        category: "Services" },
    ],
  },
  {
    id: "s8",
    name: "Additional Info",
    description: "The below information is not required to submit a request, but will be required before the event booking.",
    icon: "File",
    fields: [
      { id: "f70", label: "Expected Guest Arrival Time", type: "text", required: false, visibleToClient: true,
        placeholder: "Enter the time communicated to majority of guests to come at",
        category: "Info" },
      { id: "f71", label: "Period of time no one on site during booking", type: "text", required: false, visibleToClient: true,
        placeholder: "",
        helpText: "If there's a gap during the booking where no one will be on site (e.g., for a break between setup and event start), specify here.",
        category: "Info" },
      { id: "f72", label: "2nd Person Contact on the day of Event", type: "instructional",
        visibleToClient: true,
        fieldDescription: "Provide a backup contact in case the primary contact is unavailable on event day.",
        category: "Info" },
      { id: "f73", label: "Name", type: "text", required: false, visibleToClient: true,
        placeholder: "Enter name of emergency contact",
        category: "Info" },
      { id: "f74", label: "Phone Number", type: "number", required: false, visibleToClient: true,
        placeholder: "Enter valid phone number: (123) 123-1234",
        category: "Info" },
      { id: "f75", label: "Special Notes", type: "textarea", required: false, visibleToClient: true,
        placeholder: "Share any details or special requests that will help us tailor your event to perfection!",
        category: "Info" },
      { id: "f76", label: "Blackboard Sign Message", type: "text", required: false, visibleToClient: true,
        placeholder: "ex. Welcome to Joanna's 20th Bday Party",
        helpText: "Custom message displayed on the venue's chalkboard sign greeting your guests.",
        category: "Info" },
      { id: "f77", label: "Add-Ons", type: "multiselect", hasOptions: true, displayAs: "checkbox",
        required: false, visibleToClient: true,
        fieldDescription: "Main Hall",
        helpText: "Check any additional amenities needed for the event.",
        options: [
          { label: "Wi-Fi", infoText: "High-speed wireless internet available throughout the venue. Login credentials provided on event day." },
          { label: "Sink Access", infoText: "Access to the venue's sink for food prep, cleaning, or beverage service." },
          { label: "Mini Fridge - Floor", infoText: "Floor-standing mini fridge located in the kitchen area." },
          { label: "Mini Fridge - Counter", infoText: "Countertop mini fridge for drinks within easy reach." },
          { label: "Accessibility Elevator", infoText: "Wheelchair-accessible elevator service available throughout the venue." },
          { label: "Printer Access", infoText: "Use of the venue's printer for last-minute signage, programs, or check-in lists." },
        ],
        category: "Info" },
    ],
  },
  {
    id: "s9",
    name: "Submit Request",
    description: "Review the booking details and send the request to our team.",
    icon: "Publish",
    stepType: "checkout",
    checkout: {
      summaryItems: {
        spaceRental: true,
        spaceContentRentals: true,
        cateringCost: true,
        setupServiceCost: true,
        eventServiceCost: true,
        cleanupServiceCost: true,
        tax: true,
        securityDeposit: true,
        totalWithSecurityDeposit: true,
      },
      confirmationMessage: "Check both boxes to submit. You'll receive a confirmation email with a link to edit your request.",
      agreements: [
        { id: "agr_booking", label: "I understand that this form is only a booking request. A staff member will review availability of the space and requested items, then contact me to confirm the booking and provide an invoice.", required: true },
        { id: "agr_deposit", label: "I understand that a 50% deposit of the space rental fee is required to confirm and hold the booking date, with the remaining balance due 5 business days prior to the event.", required: true },
      ],
      submitLabel: "Submit",
      successMessage: "This would submit the booking request.",
    },
    fields: [],
  },
];

const FIELD_TYPES = [
  { type: "text",       label: "Short text",      desc: "Single-line input",     icon: "Type" },
  { type: "textarea",   label: "Long text",       desc: "Multi-line text area",  icon: "List" },
  { type: "email",      label: "Email",           desc: "Email address input",   icon: "Mail" },
  { type: "phone",      label: "Phone",           desc: "Phone number input",    icon: "Phone" },
  { type: "number",     label: "Number",          desc: "Quantity or count",     icon: "Hash" },
  { type: "select",     label: "Dropdown",        desc: "Single select from list", icon: "Chevron" },
  { type: "multiselect",label: "Multi-select",    desc: "Checkboxes / multi pick", icon: "CheckSq" },
  { type: "date",       label: "Date & time",     desc: "Single moment",         icon: "Clock" },
  { type: "daterange",  label: "Date range",      desc: "Start to end",          icon: "Cal" },
  { type: "file",       label: "File upload",     desc: "Image or document",     icon: "File" },
  { type: "price",      label: "Price",           desc: "Currency value",        icon: "Dollar" },
  { type: "toggle",     label: "Toggle",          desc: "Yes / no switch",       icon: "Toggle" },
  { type: "radio",      label: "Radio buttons",   desc: "Options with descriptions", icon: "List" },
  { type: "groupselect",label: "Grouped dropdown", desc: "Options in groups",    icon: "Sliders" },
  { type: "time",       label: "Time picker",     desc: "Time of day",           icon: "Clock" },
  { type: "checkbox",   label: "Checkbox",        desc: "Toggle with options",   icon: "CheckSq" },
  { type: "dietary",    label: "Dietary list",    desc: "Dietary restriction picker", icon: "List" },
  { type: "room",       label: "Room selector",   desc: "Visual venue picker",   icon: "Building" },
  { type: "addons",     label: "Add-on cards",    desc: "Image cards with price", icon: "Cards" },
  { type: "rental_group", label: "Rental group",  desc: "Pull from Rentals catalog", icon: "Tag" },
  { type: "extras",     label: "Extras",          desc: "Admin amount plus shared notes", icon: "Dollar" },
  { type: "separator",  label: "Separator line",  desc: "Visual divider line",   icon: "Minus" },
  { type: "instructional", label: "Instructional text", desc: "Display-only text", icon: "Info" },
];

const SIMPLE_FIELD_GROUPS = [
  {
    group: "Basic Answers",
    items: [
      { key: "short_text", type: "text", label: "Short Answer", desc: "One line of text.", icon: "Type", placeholder: "Type answer here" },
      { key: "long_text", type: "textarea", label: "Long Answer", desc: "Paragraph or notes.", icon: "List", placeholder: "Add details here" },
      { key: "email", type: "email", label: "Email", desc: "Email address.", icon: "Mail", placeholder: "name@example.com" },
      { key: "phone", type: "phone", label: "Phone", desc: "Phone number.", icon: "Phone", placeholder: "(123) 123-1234" },
      { key: "number", type: "number", label: "Number", desc: "Count or numeric answer.", icon: "Hash", placeholder: "0", min: null, max: null, step: 1 },
      { key: "extras", type: "extras", label: "Extras", desc: "Admin amount plus client/staff notes.", icon: "Dollar", linkedToPricing: true },
      { key: "date", type: "date", label: "Date", desc: "Calendar date.", icon: "Cal" },
      { key: "time", type: "time", label: "Time", desc: "Time of day.", icon: "Clock" },
      { key: "file", type: "file", label: "File Upload", desc: "Image or document.", icon: "File", acceptedFiles: "image/*,.pdf,.doc,.docx", allowMultipleFiles: false },
    ],
  },
  {
    group: "Choices",
    items: [
      { key: "single_choice", type: "radio", label: "Single Choice", desc: "Client picks one option.", icon: "List", hasOptions: true, displayAs: "radio", options: [{ label: "Option 1" }, { label: "Option 2" }] },
      { key: "multiple_choice", type: "multiselect", label: "Multiple Choice", desc: "Client can check more than one.", icon: "CheckSq", hasOptions: true, displayAs: "checkbox", options: [{ label: "Option 1" }, { label: "Option 2" }] },
      { key: "delivery_options", type: "multiselect", label: "Delivery Options", desc: "Uses delivery fees from Site Settings.", icon: "Truck", hasOptions: true, displayAs: "checkbox", dynamicSource: "delivery_options", linkedToPricing: true, options: [] },
      { key: "dropdown", type: "select", label: "Dropdown", desc: "Client picks from a compact list.", icon: "Chevron", hasOptions: true, displayAs: "select", options: [{ label: "Option 1" }, { label: "Option 2" }] },
      { key: "checkbox", type: "toggle", label: "Checkbox", desc: "One required agreement or yes/no check.", icon: "CheckSq" },
    ],
  },
  {
    group: "Display",
    items: [
      { key: "info_text", type: "instructional", label: "Info Text", desc: "Read-only instructions.", icon: "Info" },
      { key: "separator", type: "separator", label: "Section Divider", desc: "Visual divider between fields.", icon: "Minus" },
    ],
  },
];


const ROOMS = [
  { id: "main",    name: "Main Hall",    capacity: "Up to 250 guests", hourly: "$450/hr", min: "6 hr min" },
  { id: "large",   name: "Large Room",   capacity: "Up to 80 guests",  hourly: "$220/hr", min: "4 hr min" },
  { id: "small",   name: "Small Room",   capacity: "Up to 4 guests",   hourly: "$60/hr",  min: "2 hr min" },
  { id: "lounge",  name: "Lounge Area",  capacity: "Up to 20 guests",  hourly: "$100/hr", min: "2 hr min" },
  { id: "patio",   name: "Back Patio",   capacity: "Up to 40 guests",  hourly: "$140/hr", min: "Add-on" },
];

export { SAMPLE_STEPS, FIELD_TYPES, SIMPLE_FIELD_GROUPS, ROOMS };
